
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.115.21.244:3306/user_center?useSSL=true
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: user-center
server:
  port: 9090